previewsEnabled: true
services:
  - type: web
    plan: free
    name: app
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py